create table audit_log
(
    id              bigint generated by default as identity
        primary key,
    created_at      timestamp with time zone not null,
    doctor_id       bigint,
    drugs_dispensed text,
    drugs_requested text,
    failure_reason  varchar(255),
    patient_id      bigint,
    pharmacy_id     bigint,
    prescription_id bigint,
    status          varchar(255)             not null
        constraint audit_log_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'FULFILLED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])),
    updated_at      timestamp with time zone not null
);

alter table audit_log
    owner to myuser;

create table drug
(
    id         bigint                   not null
        primary key,
    created_at timestamp with time zone not null,
    name       varchar(255),
    updated_at timestamp with time zone not null
);

alter table drug
    owner to myuser;

create table drug_lot
(
    id           bigint                   not null
        primary key,
    batch_number varchar(255),
    created_at   timestamp with time zone not null,
    expiry_date  timestamp(6) with time zone,
    manufacturer varchar(255),
    name         varchar(255),
    stock        integer,
    updated_at   timestamp with time zone not null,
    drug_id      bigint                   not null
        constraint fkqqe3n3xirm7235jqix7cwa4hg
            references drug
);

alter table drug_lot
    owner to myuser;

create table pharmacy
(
    id         bigint                   not null
        primary key,
    created_at timestamp with time zone not null,
    location   varchar(255),
    name       varchar(255),
    updated_at timestamp with time zone not null
);

alter table pharmacy
    owner to myuser;

create table pharmacy_drug_allocation
(
    id               bigint                   not null
        primary key,
    allocation_limit integer,
    created_at       timestamp with time zone not null,
    expiry_date      timestamp(6) with time zone,
    updated_at       timestamp with time zone not null,
    version          integer,
    drug_id          bigint                   not null
        constraint fkbd8jpdq8c42vghkm61xf7ad3d
            references drug,
    drug_lot_id      bigint                   not null
        constraint fkl77qjdnoeeyuofc1b3pqxvpki
            references drug_lot,
    pharmacy_id      bigint                   not null
        constraint fkr3cyy0crksky80psdtayhbyfs
            references pharmacy
);

alter table pharmacy_drug_allocation
    owner to myuser;

create index idx_drug_id
    on pharmacy_drug_allocation (drug_id);

create table prescription
(
    id          bigint                   not null
        primary key,
    created_at  timestamp with time zone not null,
    doctor_id   bigint,
    patient_id  bigint,
    pharmacy_id bigint,
    status      varchar(255)             not null
        constraint prescription_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'FULFILLED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])),
    updated_at  timestamp with time zone not null
);

alter table prescription
    owner to myuser;

create table prescription_drug
(
    id              bigint                   not null
        primary key,
    created_at      timestamp with time zone not null,
    dosage          integer,
    drug_id         bigint,
    updated_at      timestamp with time zone not null,
    prescription_id bigint                   not null
        constraint fkom0pg7l17e3uqov7dog7owsm6
            references prescription
);

alter table prescription_drug
    owner to myuser;

